image:
  file: .gitpod.dockerfile

tasks:
  - name: Run
    init: func host start

ports:
  - name: Azure Function
    description: Azure Function local emulator preview
    port: 7071
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
vscode:
  extensions:
    - ms-vscode.azure-account
    - ms-azuretools.vscode-azurefunctions
    - ms-azuretools.vscode-azureresourcegroups
    - ms-python.python